# Generated by Django 6.0.5 on 2026-09-02 06:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_remove_project_user_project_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultEmbeddingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('name', models.CharField(default='Default System Embedding', help_text='The display name for the default embedding configuration.', max_length=100)),
                ('role', models.CharField(help_text="Unique identifier for the embedding role (e.g., 'default_search', 'code_retrieval').", max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Default Embedding Configuration',
                'verbose_name_plural': 'Default Embedding Configurations',
            },
        ),
        migrations.CreateModel(
            name='EmbeddingConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('name', models.CharField(default='Default Embedding', help_text='The display name for this embedding configuration.', max_length=100)),
                ('role', models.CharField(help_text="The role or purpose of this embedding configuration (e.g., 'search', 'recommendation').", max_length=50)),
                ('provider_id', models.UUIDField(default=uuid.uuid4, help_text='The ID of the LLM provider configuration used for embeddings.')),
                ('model_family_id', models.UUIDField(default=uuid.uuid4, help_text='The ID of the embedding model family used for generating vectors.')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Specific runtime parameters for the embedding model (e.g., dimensions, chunk_size).')),
                ('project', models.OneToOneField(help_text='The project this embedding configuration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='projects.project')),
            ],
            options={
                'verbose_name': 'Embedding Configuration',
                'verbose_name_plural': 'Embedding Configurations',
                'constraints': [models.UniqueConstraint(fields=('project', 'role'), name='unique_embedding_role_per_project')],
            },
        ),
    ]
