# Generated by Django 6.0.5 on 2026-08-24 02:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_remove_project_user_project_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text="The unique name used to identify this agent role (e.g., 'Dichotomy Suggester').", max_length=100, unique=True)),
                ('system_prompt', models.TextField(help_text='The instruction set given to the LLM to define its persona and task.')),
                ('prompt_template', models.TextField(help_text='The full template text used to render the final prompt, containing all static text and {{variable}} placeholders.')),
                ('template_variables', models.JSONField(blank=True, default=dict, help_text="A dictionary defining the dynamic variables required by the prompt_template and their data source/type (e.g., {'final_question_draft': 'DB_FACTS', 'latest_user_input': 'CURRENT_TURN'}).")),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='The JSON schema defining the required output structure for the LLM response.')),
                ('output_format', models.CharField(choices=[('JSON', 'JSON'), ('TEXT', 'TEXT')], default='TEXT', help_text="The expected format of the LLM's output (e.g., 'TEXT', 'JSON').", max_length=20)),
                ('llm_parameters', models.JSONField(blank=True, default=dict, help_text='Specific runtime parameters for the LLM call (e.g., temperature, top_p, max_tokens).')),
                ('provider_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The ID of the LLM provider configuration used for this agent.')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The ID of the user owning this project.')),
            ],
            options={
                'verbose_name': 'Agent Configuration',
                'verbose_name_plural': 'Agent Configurations',
            },
        ),
        migrations.CreateModel(
            name='AgentProjectRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentconfig')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='projects',
            field=models.ManyToManyField(related_name='agent', through='agents.AgentProjectRelation', to='projects.project'),
        ),
    ]
