# Generated by Django 6.0.5 on 2026-08-24 03:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAgentConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('role', models.CharField(help_text="The unique name used to identify this agent role (e.g., 'Dichotomy Suggester').", max_length=100, unique=True)),
                ('system_prompt', models.TextField(help_text='The instruction set given to the LLM to define its persona and task.')),
                ('prompt_template', models.TextField(help_text='The full template text used to render the final prompt, containing all static text and {{variable}} placeholders.')),
                ('template_variables', models.JSONField(blank=True, default=dict, help_text="A dictionary defining the dynamic variables required by the prompt_template and their data source/type (e.g., {'final_question_draft': 'DB_FACTS', 'latest_user_input': 'CURRENT_TURN'}).")),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='The JSON schema defining the required output structure for the LLM response.')),
                ('output_format', models.CharField(choices=[('JSON', 'JSON'), ('TEXT', 'TEXT')], default='TEXT', help_text="The expected format of the LLM's output (e.g., 'TEXT', 'JSON').", max_length=20)),
                ('llm_parameters', models.JSONField(blank=True, default=dict, help_text='Specific runtime parameters for the LLM call (e.g., temperature, top_p, max_tokens).')),
            ],
            options={
                'verbose_name': 'Default Agent Configuration',
                'verbose_name_plural': 'Default Agent Configurations',
            },
        ),
    ]
