# Generated by Django 6.0.5 on 2026-08-24 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_defaultagentconfig'),
        ('projects', '0003_remove_project_user_project_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprojectrelation',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='agentprojectrelation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='agentconfig',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='agentconfig',
            name='user_id',
        ),
        migrations.AddField(
            model_name='agentconfig',
            name='project',
            field=models.ForeignKey(default='', help_text='The project this agent configuration belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='role',
            field=models.CharField(help_text="The unique name used to identify this agent role (e.g., 'Dichotomy Suggester').", max_length=100),
        ),
        migrations.AddConstraint(
            model_name='agentconfig',
            constraint=models.UniqueConstraint(fields=('project', 'role'), name='unique_agent_role_per_project'),
        ),
        migrations.DeleteModel(
            name='AgentProjectRelation',
        ),
    ]
