# Generated by Django 6.0.5 on 2026-08-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_remove_agentprojectrelation_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='purpose',
            field=models.TextField(default='', help_text="A brief description of the agent's purpose and intended use case."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultagentconfig',
            name='purpose',
            field=models.TextField(default='', help_text="A brief description of the agent's purpose and intended use case."),
            preserve_default=False,
        ),
    ]
