# Generated by Django 6.0.5 on 2026-08-24 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentconfig_purpose_defaultagentconfig_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfig',
            name='model_family_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='The ID of the LLM model configuration used for this agent.'),
        ),
        migrations.AlterField(
            model_name='agentconfig',
            name='provider_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='The ID of the LLM provider configuration used for this agent.'),
        ),
    ]
