# Generated by Django 6.0.5 on 2026-09-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentconfig_model_family_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultagentconfig',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
