# Generated by Django 6.0.5 on 2026-08-14 11:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The ID of the user owning this project.'),
        ),
    ]
