# Generated by Django 6.0.5 on 2026-08-14 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('file_name', models.CharField(help_text='Original file name (e.g., "Q3_Procurement_Plan.pdf")', max_length=255)),
                ('file_size', models.CharField(help_text='Human-readable file size (e.g., "2.4 MB")', max_length=50)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('csv', 'CSV')], default='pdf', help_text='File format extension', max_length=20)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('ERROR', 'Error'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused')], default='IDLE', help_text='Processing status of the file', max_length=20)),
                ('file_path', models.CharField(blank=True, help_text='Relative path or S3 key of the stored file.', max_length=512, null=True)),
                ('storage_type', models.CharField(default='local', help_text='Storage backend type used for this file.', max_length=52)),
            ],
            options={
                'verbose_name': 'Repository File',
                'verbose_name_plural': 'Repository Files',
                'db_table': 'repository_files',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChunkData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this entity.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The timestamp when this record was first created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The timestamp when this record was last modified.')),
                ('alignment', models.JSONField(default=dict, help_text='Layer 1: Contextual target questions, scope domain, impact level, and boundaries')),
                ('concept', models.JSONField(default=dict, help_text='Layer 2: High-level concepts and structural propositions')),
                ('keywords', models.JSONField(default=dict, help_text='Layer 3: Bound semantic triples (Subject-Predicate-Object) and thematic tags')),
                ('evidence', models.JSONField(default=dict, help_text='Layer 4: Exact verbatim excerpt text and source location')),
                ('file', models.ForeignKey(db_column='file_id', help_text='Parent document reference', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='repositories.repositoryfile')),
            ],
            options={
                'verbose_name': 'Chunk Data',
                'verbose_name_plural': 'Chunk Data',
                'db_table': 'repository_chunks',
            },
        ),
    ]
