# Generated by Django 6.0.5 on 2026-08-14 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_user_project_user_id'),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='project',
            field=models.ForeignKey(default='', help_text='Foreign key to the associated project.', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.project'),
            preserve_default=False,
        ),
    ]
