# Generated by Django 6.0.5 on 2026-08-18 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories', '0002_repositoryfile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositoryfile',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='The ID of the user owning this file.'),
        ),
    ]
